UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bbb} \Phi_{b} c_{1}) c_{1}) (\Phi_{cbbb} c_{1} \Phi_{bb} \Phi_{bb} c_{1})' where id=1;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=1;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{1}) (\Phi_{cb} c_{1} \Phi_{cb})' where id=2;
UPDATE resuelve SET variables=';p,q' where teoremaid=2;
UPDATE teorema SET enunciado='= (\Phi_{cbb} c_{1} \Phi_{b(b,)} c_{1}) (\Phi_{b} \Phi_{K})' where id=3;
UPDATE resuelve SET variables=';p,q' where teoremaid=3;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{(bb,)} c_{1}) c_{1}) (\Phi_{b} \Phi_{K})' where id=4;
UPDATE resuelve SET variables=';p,q' where teoremaid=4;
UPDATE teorema SET enunciado='= (\Phi_{b} \Phi_{K}) (\Phi_{cb} c_{1} (\Phi_{(b,cb)} c_{1}))' where id=5;
UPDATE resuelve SET variables=';p,q' where teoremaid=5;
UPDATE teorema SET enunciado='= (\Phi_{b} \Phi_{K}) (\Phi_{ccb} c_{1} c_{1} \Phi_{cb(b,)})' where id=6;
UPDATE resuelve SET variables=';p,q' where teoremaid=6;
UPDATE teorema SET enunciado='= (\Phi_{(b,)} c_{1}) (\Phi_{K} c_{8})' where id=7;
UPDATE resuelve SET variables=';q' where teoremaid=7;
UPDATE teorema SET enunciado='= \Phi_{} (\Phi_{cb} c_{8} c_{1})' where id=8;
UPDATE resuelve SET variables=';q' where teoremaid=8;
UPDATE teorema SET enunciado='= T c_{8}' where id=9;
UPDATE resuelve SET variables=';' where teoremaid=9;
UPDATE teorema SET enunciado='= (c_{7} c_{8}) c_{9}' where id=11;
UPDATE resuelve SET variables=';' where teoremaid=11;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bb} c_{7}) c_{1}) (\Phi_{bb} \Phi_{b} c_{6})' where id=13;
UPDATE resuelve SET variables=';q,p' where teoremaid=13;
UPDATE teorema SET enunciado='= (\Phi_{bbb} \Phi_{b} c_{1} c_{7}) (\Phi_{cbb} c_{7} \Phi_{bb} c_{1})' where id=14;
UPDATE resuelve SET variables=';q,p' where teoremaid=14;
UPDATE teorema SET enunciado='= \Phi_{} (\Phi_{bb} c_{7} c_{7})' where id=15;
UPDATE resuelve SET variables=';p' where teoremaid=15;
UPDATE teorema SET enunciado='= c_{8} (c_{7} c_{9})' where id=16;
UPDATE resuelve SET variables=';' where teoremaid=16;
UPDATE teorema SET enunciado='= (\Phi_{cbb} c_{7} \Phi_{bb} c_{1}) (\Phi_{bb} \Phi_{b} c_{6})' where id=17;
UPDATE resuelve SET variables=';q,p' where teoremaid=17;
UPDATE teorema SET enunciado='= (\Phi_{b} (c_{1} c_{9})) (\Phi_{b} c_{7})' where id=18;
UPDATE resuelve SET variables=';p' where teoremaid=18;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{6}) (\Phi_{cb} c_{6} \Phi_{cb})' where id=19;
UPDATE resuelve SET variables=';p,q' where teoremaid=19;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bbb} \Phi_{b} c_{6}) c_{6}) (\Phi_{cbbb} c_{6} \Phi_{bb} \Phi_{bb} c_{6})' where id=20;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=20;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bbb} \Phi_{b} c_{6}) c_{1}) (\Phi_{cbbb} c_{6} \Phi_{bb} \Phi_{bb} c_{1})' where id=21;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=21;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bbb} \Phi_{b} c_{1}) c_{6}) (\Phi_{cbbb} c_{6} \Phi_{bb} \Phi_{bb} c_{1})' where id=22;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=22;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{4}) (\Phi_{cb} c_{4} \Phi_{cb})' where id=23;
UPDATE resuelve SET variables=';p,q' where teoremaid=23;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bbb} \Phi_{b} c_{4}) c_{4}) (\Phi_{cbbb} c_{4} \Phi_{bb} \Phi_{bb} c_{4})' where id=24;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=24;
UPDATE teorema SET enunciado='= \Phi_{} (\Phi_{(b,)} c_{4})' where id=25;
UPDATE resuelve SET variables=';p' where teoremaid=25;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{4} \Phi_{bcb} c_{1}) c_{4}) (\Phi_{ccbb} \Phi_{cbb} c_{4} \Phi_{ccb} c_{1})' where id=26;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=26;
UPDATE teorema SET enunciado='= (\Phi_{cbb} c_{7} \Phi_{bb} c_{4}) (\Phi_{bb} \Phi_{b} c_{2})' where id=66;
UPDATE resuelve SET variables=';q,p' where teoremaid=66;
UPDATE teorema SET enunciado='= (\Phi_{c(bb,)} c_{5} \Phi_{bcb} c_{1}) (\Phi_{cb} c_{2} \Phi_{cb})' where id=67;
UPDATE resuelve SET variables=';p,q' where teoremaid=67;
UPDATE teorema SET enunciado='= (\Phi_{K} T) (\Phi_{(bb,)} c_{4} c_{7})' where id=27;
UPDATE resuelve SET variables=';p' where teoremaid=27;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{8}) (\Phi_{b} (c_{4} c_{8}))' where id=28;
UPDATE resuelve SET variables=';p' where teoremaid=28;
UPDATE teorema SET enunciado='= \Phi_{} (\Phi_{b} (c_{4} c_{9}))' where id=29;
UPDATE resuelve SET variables=';p' where teoremaid=29;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{4} \Phi_{bcb} c_{4}) c_{4}) (\Phi_{ccbb} \Phi_{cbb} c_{4} \Phi_{ccb} c_{4})' where id=30;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=30;
UPDATE teorema SET enunciado='= (\Phi_{cc(bb,)} c_{7} c_{4} \Phi_{bcbb} c_{1}) (\Phi_{cb} c_{4} \Phi_{cb})' where id=31;
UPDATE resuelve SET variables=';p,q' where teoremaid=31;
UPDATE teorema SET enunciado='= (\Phi_{b} \Phi_{K}) (\Phi_{c(ccb,)} c_{4} c_{7} c_{4} (\Phi_{(bcbb,cb)} c_{1}))' where id=32;
UPDATE resuelve SET variables=';p,q' where teoremaid=32;
UPDATE teorema SET enunciado='= (\Phi_{(cb,b)} c_{1} \Phi_{cbb} c_{4}) (\Phi_{bb} (\Phi_{(b,b)} c_{1}) c_{5})' where id=33;
UPDATE resuelve SET variables=';q,p' where teoremaid=33;
UPDATE teorema SET enunciado='= (\Phi_{(bb,b)} (\Phi_{(bb,b)} c_{1}) c_{4} c_{1}) (\Phi_{bb} \Phi_{b} c_{5})' where id=34;
UPDATE resuelve SET variables=';q,p' where teoremaid=34;
UPDATE teorema SET enunciado='= (\Phi_{(cb,b)} c_{1} (\Phi_{(bcbb,)} c_{1}) c_{4}) (\Phi_{bb} \Phi_{b} c_{5})' where id=35;
UPDATE resuelve SET variables=';q,p' where teoremaid=35;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{4}) (\Phi_{(bb,b)} (\Phi_{(bb,b)} c_{1}) c_{1} c_{5})' where id=36;
UPDATE resuelve SET variables=';q,p' where teoremaid=36;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{4}) (\Phi_{(cbb,b)} c_{1} \Phi_{b(b,b)} c_{1} c_{5})' where id=37;
UPDATE resuelve SET variables=';q,p' where teoremaid=37;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{5}) (\Phi_{cb} c_{5} \Phi_{cb})' where id=38;
UPDATE resuelve SET variables=';p,q' where teoremaid=38;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bbb} \Phi_{b} c_{5}) c_{5}) (\Phi_{cbbb} c_{5} \Phi_{bb} \Phi_{bb} c_{5})' where id=39;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=39;
UPDATE teorema SET enunciado='= \Phi_{} (\Phi_{(b,)} c_{5})' where id=40;
UPDATE resuelve SET variables=';p' where teoremaid=40;
UPDATE teorema SET enunciado='= \Phi_{} (\Phi_{b} (c_{5} c_{8}))' where id=41;
UPDATE resuelve SET variables=';p' where teoremaid=41;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{9}) (\Phi_{b} (c_{5} c_{9}))' where id=42;
UPDATE resuelve SET variables=';p' where teoremaid=42;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{5} \Phi_{bcb} c_{5}) c_{5}) (\Phi_{ccbb} \Phi_{cbb} c_{5} \Phi_{ccb} c_{5})' where id=43;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=43;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{9}) (\Phi_{(bb,)} c_{5} c_{7})' where id=44;
UPDATE resuelve SET variables=';p' where teoremaid=44;
UPDATE teorema SET enunciado='= (\Phi_{b} \Phi_{K}) (\Phi_{c(cb,)} c_{4} c_{5} \Phi_{cbcb})' where id=45;
UPDATE resuelve SET variables=';p,q' where teoremaid=45;
UPDATE teorema SET enunciado='= (\Phi_{b} \Phi_{K}) (\Phi_{c(cb,)} c_{5} c_{4} \Phi_{cbcb})' where id=46;
UPDATE resuelve SET variables=';p,q' where teoremaid=46;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{5}) (\Phi_{cbb} c_{7} (\Phi_{(bbb,)} c_{5}) c_{4})' where id=47;
UPDATE resuelve SET variables=';q,p' where teoremaid=47;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{4}) (\Phi_{cbb} c_{7} (\Phi_{(bbb,)} c_{4}) c_{5})' where id=48;
UPDATE resuelve SET variables=';q,p' where teoremaid=48;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{4} \Phi_{bcb} c_{5}) c_{4}) (\Phi_{ccbb} \Phi_{cbb} c_{4} \Phi_{ccb} c_{5})' where id=49;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=49;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{5} \Phi_{bcb} c_{4}) c_{5}) (\Phi_{ccbb} \Phi_{cbb} c_{5} \Phi_{ccb} c_{4})' where id=50;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=50;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} c_{7} \Phi_{bb} c_{4} c_{7}) (\Phi_{bb} (\Phi_{bb} c_{7}) c_{5})' where id=51;
UPDATE resuelve SET variables=';q,p' where teoremaid=51;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} c_{7} \Phi_{bb} c_{5} c_{7}) (\Phi_{bb} (\Phi_{bb} c_{7}) c_{4})' where id=52;
UPDATE resuelve SET variables=';q,p' where teoremaid=52;
UPDATE teorema SET enunciado='= (\Phi_{cc(bbb,)} c_{7} c_{5} \Phi_{bcbb} c_{1} c_{7}) (\Phi_{cb} c_{5} \Phi_{cb})' where id=53;
UPDATE resuelve SET variables=';p,q' where teoremaid=53;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{K} c_{7}) (\Phi_{c(ccb,)} c_{5} c_{7} c_{5} (\Phi_{(bcbb,cb)} c_{1}))' where id=54;
UPDATE resuelve SET variables=';p,q' where teoremaid=54;
UPDATE teorema SET enunciado='= (\Phi_{c(bb,)} c_{5} (\Phi_{bbcb} \Phi_{K}) c_{1}) (\Phi_{cbc(cb,)} c_{1} \Phi_{bb} c_{5} c_{5} (\Phi_{(bcb,cbb)} c_{1}))' where id=55;
UPDATE resuelve SET variables=';p,r,q' where teoremaid=55;
UPDATE teorema SET enunciado='= (\Phi_{c(c(b,bb),)} c_{5} c_{1} (\Phi_{ccbbcb} c_{5}) \Phi_{bbcb} c_{1}) (\Phi_{cbcb} c_{1} \Phi_{bb} c_{5} \Phi_{cbb})' where id=56;
UPDATE resuelve SET variables=';p,r,q' where teoremaid=56;
UPDATE teorema SET enunciado='= (\Phi_{c((ccb,b),)} c_{5} c_{1} \Phi_{bcb} (\Phi_{ccbbbcb} c_{5}) c_{1}) (\Phi_{cbcb} c_{1} \Phi_{bb} c_{5} \Phi_{cbb})' where id=57;
UPDATE resuelve SET variables=';p,r,q' where teoremaid=57;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{K} \Phi_{K}) (\Phi_{cc(cc(cb,),)} c_{1} c_{5} c_{1} (\Phi_{(bbcb,cbb)} c_{1}) c_{5} (\Phi_{(ccccbbcb,b)} c_{5}))' where id=58;
UPDATE resuelve SET variables=';p,r,q' where teoremaid=58;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{K} \Phi_{K}) (\Phi_{cc(ccc(cb,),)} c_{1} c_{5} c_{1} \Phi_{b(bcb,cbb)} c_{1} c_{5} (\Phi_{(cccccbbcb,b)} c_{5}))' where id=59;
UPDATE resuelve SET variables=';p,r,q' where teoremaid=59;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{5}) (\Phi_{cb} c_{1} (\Phi_{(bcb,)} c_{5}))' where id=60;
UPDATE resuelve SET variables=';q,p' where teoremaid=60;
UPDATE teorema SET enunciado='= (\Phi_{(ccbb,b)} c_{5} \Phi_{bb} \Phi_{cbbb} c_{1} c_{1}) (\Phi_{ccbb} (\Phi_{(bcb,b)} c_{5}) c_{1} \Phi_{ccb} c_{1})' where id=61;
UPDATE resuelve SET variables=';q,r,p' where teoremaid=61;
UPDATE teorema SET enunciado='= (\Phi_{(cbbb,b)} c_{7} (\Phi_{(bbb,b)} c_{4}) c_{5} c_{7} c_{5}) (\Phi_{bb} \Phi_{b} c_{1})' where id=62;
UPDATE resuelve SET variables=';q,p' where teoremaid=62;
UPDATE teorema SET enunciado='= (\Phi_{c(bbb,b)} c_{7} (\Phi_{(bb,bb)} c_{4}) c_{5} c_{7} c_{5}) (\Phi_{bb} \Phi_{b} c_{6})' where id=63;
UPDATE resuelve SET variables=';q,p' where teoremaid=63;
UPDATE teorema SET enunciado='= (\Phi_{(bb,b)} \Phi_{bb} c_{1} c_{4}) (\Phi_{bb} \Phi_{b} c_{2})' where id=64;
UPDATE resuelve SET variables=';q,p' where teoremaid=64;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{2}) (\Phi_{cb} c_{3} \Phi_{cb})' where id=65;
UPDATE resuelve SET variables=';p,q' where teoremaid=65;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} c_{7} \Phi_{bb} c_{2} c_{7}) (\Phi_{cb} c_{2} \Phi_{cb})' where id=68;
UPDATE resuelve SET variables=';p,q' where teoremaid=68;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{5} \Phi_{bcb} c_{1}) c_{5}) (\Phi_{ccbb} \Phi_{cbb} c_{2} \Phi_{ccb} c_{1})' where id=69;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=69;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{2} \Phi_{bcb} c_{1}) c_{2}) (\Phi_{ccbb} \Phi_{cbb} c_{2} \Phi_{ccb} c_{1})' where id=70;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=70;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{2} \Phi_{bcb} c_{2}) c_{2}) (\Phi_{ccbb} \Phi_{cbb} c_{2} \Phi_{ccb} c_{2})' where id=71;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=71;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bbb} \Phi_{b} c_{2}) c_{2}) (\Phi_{cbbb} c_{5} \Phi_{bb} \Phi_{bb} c_{2})' where id=72;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=72;
UPDATE teorema SET enunciado='= (\Phi_{cbb} c_{7} \Phi_{bb} c_{1}) (\Phi_{bb} (\Phi_{bb} c_{7}) c_{1})' where id=12;
UPDATE resuelve SET variables=';q,p' where teoremaid=12;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{5}) (\Phi_{bb} (\Phi_{(bb,)} c_{5}) c_{2})' where id=73;
UPDATE resuelve SET variables=';q,p' where teoremaid=73;
UPDATE teorema SET enunciado='= (\Phi_{b} \Phi_{K}) (\Phi_{(cb,b)} c_{5} \Phi_{cbb} c_{2})' where id=74;
UPDATE resuelve SET variables=';p,q' where teoremaid=74;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} c_{8})) (\Phi_{bb} (\Phi_{(bb,)} c_{4}) c_{2})' where id=75;
UPDATE resuelve SET variables=';q,p' where teoremaid=75;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{2}) (\Phi_{(cb,b)} c_{4} \Phi_{cbb} c_{2})' where id=76;
UPDATE resuelve SET variables=';p,q' where teoremaid=76;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{1}) (\Phi_{(bb,b)} (\Phi_{(bb,b)} c_{2}) c_{5} c_{4})' where id=77;
UPDATE resuelve SET variables=';q,p' where teoremaid=77;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{8}) (\Phi_{(b,)} c_{2})' where id=78;
UPDATE resuelve SET variables=';p' where teoremaid=78;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{8}) (\Phi_{b} (c_{2} c_{8}))' where id=79;
UPDATE resuelve SET variables=';p' where teoremaid=79;
UPDATE teorema SET enunciado='= \Phi_{} (\Phi_{cb} c_{8} c_{2})' where id=80;
UPDATE resuelve SET variables=';p' where teoremaid=80;
UPDATE teorema SET enunciado='= (\Phi_{b} c_{7}) (\Phi_{b} (c_{2} c_{9}))' where id=81;
UPDATE resuelve SET variables=';p' where teoremaid=81;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{8}) (\Phi_{cb} c_{9} c_{2})' where id=82;
UPDATE resuelve SET variables=';p' where teoremaid=82;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{bb} (\Phi_{(bb,)} c_{2}) c_{4})' where id=83;
UPDATE resuelve SET variables=';q,p' where teoremaid=83;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{c(bb,)} c_{5} \Phi_{bcb} c_{2})' where id=84;
UPDATE resuelve SET variables=';p,q' where teoremaid=84;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(bb,b)} (\Phi_{(bb,b)} c_{2}) c_{4} c_{5})' where id=85;
UPDATE resuelve SET variables=';q,p' where teoremaid=85;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{(cccb,b)} c_{2} \Phi_{bcbcb} c_{4} (\Phi_{ccc(bbb,)} c_{5}) c_{4})' where id=86;
UPDATE resuelve SET variables=';q,p,r' where teoremaid=86;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{cbb} c_{5} (\Phi_{(bbb,b)} (\Phi_{(bb,b)} c_{2}) c_{5}) c_{4})' where id=87;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=87;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(cbb,b)} c_{5} \Phi_{b(bb,)} c_{2} c_{2})' where id=88;
UPDATE resuelve SET variables=';q,p' where teoremaid=88;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} c_{4} \Phi_{bb} \Phi_{bb} c_{2}) (\Phi_{(ccbb,b)} c_{5} \Phi_{bb} \Phi_{cbbb} c_{2} c_{2})' where id=89;
UPDATE resuelve SET variables=';r,q,p' where teoremaid=89;
UPDATE teorema SET enunciado='= (\Phi_{b} \Phi_{K}) (\Phi_{(cbb,b)} c_{7} (\Phi_{(bbb,b)} c_{5}) c_{2} c_{2})' where id=90;
UPDATE resuelve SET variables=';r,p' where teoremaid=90;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{1}) (\Phi_{(cb,b)} c_{2} (\Phi_{(bcb,b)} c_{5}) c_{2})' where id=91;
UPDATE resuelve SET variables=';q,p' where teoremaid=91;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(c(cbb,),b)} c_{2} c_{5} (\Phi_{(bb,(bcb,b))} c_{2}) c_{1} c_{2})' where id=92;
UPDATE resuelve SET variables=';q,p' where teoremaid=92;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{(cccbb,b)} c_{2} \Phi_{b(bb,cb)} c_{5} (\Phi_{c(ccbbb,)} c_{2}) c_{2} c_{2})' where id=93;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=93;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{(cccbb,b)} c_{2} \Phi_{b(bb,cb)} c_{5} (\Phi_{c(ccbbb,)} c_{1}) c_{2} c_{2})' where id=94;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=94;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{(cccbb,b)} c_{2} \Phi_{b(bb,cb)} c_{5} (\Phi_{c(ccbbb,)} c_{2}) c_{1} c_{2})' where id=95;
UPDATE resuelve SET variables=';r,p,q' where teoremaid=95;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{c(ccb,)} c_{1} c_{1} (\Phi_{(bbb,b)} c_{2}) \Phi_{(cbbb,b)})' where id=96;
UPDATE resuelve SET variables=';E,f,e' where teoremaid=96;
UPDATE teorema SET enunciado='= (\Phi_{cb} c_{1} (\Phi_{(bbb,b)} \Phi_{bb} c_{5})) (\Phi_{cbb} c_{1} \Phi_{bb} (\Phi_{(bb,b)} c_{5}))' where id=97;
UPDATE resuelve SET variables=';E,f,e' where teoremaid=97;
UPDATE teorema SET enunciado='= (\Phi_{cb} c_{1} (\Phi_{(cbbbb,b)} c_{5} \Phi_{bbb} \Phi_{bb} c_{2})) (\Phi_{cbcb} c_{1} \Phi_{bb} c_{5} (\Phi_{(bbb,bb)} \Phi_{bb} c_{2}))' where id=99;
UPDATE resuelve SET variables=';E,f,e,q' where teoremaid=99;
UPDATE teorema SET enunciado='= (\Phi_{bbc} \Phi_{b} c_{2} c_{8}) (\Phi_{b} (\Phi_{(bb,)} c_{2}))' where id=100;
UPDATE resuelve SET variables=';E,p' where teoremaid=100;
UPDATE teorema SET enunciado='= (\Phi_{cbbbc} c_{5} \Phi_{bb} \Phi_{bb} c_{2} c_{8}) (\Phi_{cb} c_{5} (\Phi_{(bbb,b)} \Phi_{bb} c_{2}))' where id=101;
UPDATE resuelve SET variables=';E,p,q' where teoremaid=101;
UPDATE teorema SET enunciado='= (\Phi_{cbb} c_{9} \Phi_{bc} c_{2}) (\Phi_{(bb,)} \Phi_{bc} c_{2})' where id=102;
UPDATE resuelve SET variables=';p,E' where teoremaid=102;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{cbbb} c_{9} \Phi_{bc} c_{2}) c_{4}) (\Phi_{bb} (\Phi_{(bbb,)} \Phi_{bc} c_{2}) c_{4})' where id=103;
UPDATE resuelve SET variables=';q,p,E' where teoremaid=103;
UPDATE teorema SET enunciado='= (\Phi_{bbc} \Phi_{b} c_{5} c_{8}) (\Phi_{b} (\Phi_{(bb,)} c_{5}))' where id=104;
UPDATE resuelve SET variables=';E,p' where teoremaid=104;
UPDATE teorema SET enunciado='= (\Phi_{bbc} \Phi_{b} c_{4} c_{9}) (\Phi_{b} (\Phi_{(bb,)} c_{4}))' where id=105;
UPDATE resuelve SET variables=';E,p' where teoremaid=105;
UPDATE teorema SET enunciado='= (\Phi_{(cbbc,bc)} c_{7} (\Phi_{(bbb,b)} c_{4}) c_{5} c_{9} c_{5} c_{8}) (\Phi_{b} \Phi_{b})' where id=106;
UPDATE resuelve SET variables=';E,p' where teoremaid=106;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bcc(ccb,b)} c_{11} c_{16} (\Phi_{(bb,b)} c_{1}) c_{11} c_{15} (\Phi_{(bcb,bcbb)} c_{2}) c_{16}))' where id=107;
UPDATE resuelve SET variables='A,B,x;' where teoremaid=107;
UPDATE teorema SET enunciado='= T (c_{13} (\Phi_{bbb} c_{11} (\Phi_{bb} c_{7}) c_{16}))' where id=108;
UPDATE resuelve SET variables='A,x;' where teoremaid=108;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bcc(ccb,b)} c_{11} c_{16} (\Phi_{(bb,b)} c_{1}) c_{11} c_{15} (\Phi_{(bcb,bcbb)} c_{1}) c_{16}))' where id=109;
UPDATE resuelve SET variables='A,B,x;' where teoremaid=109;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bccbb} c_{11} c_{15} (\Phi_{(b(bb,b),b)} c_{1} c_{4}) (\Phi_{bcbcbb} c_{13} c_{16} (\Phi_{bbb} c_{11})) c_{15}))' where id=110;
UPDATE resuelve SET variables='a,b,A,x;' where teoremaid=110;
UPDATE teorema SET enunciado='= (\Phi_{K} T) (\Phi_{bccb} c_{11} c_{16} (\Phi_{(b(bcb,b),b)} c_{1} c_{5}) (\Phi_{bcb(cb,b)} c_{13} c_{16} (\Phi_{bbb} c_{11})))' where id=111;
UPDATE resuelve SET variables='U,A,x;P' where teoremaid=111;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bcbcccbbb} c_{13} c_{16} (\Phi_{bbb} c_{11}) \Phi_{cb} c_{16} c_{14} (\Phi_{(bcbcb,b)} c_{1}) \Phi_{b} c_{16}))' where id=112;
UPDATE resuelve SET variables='B,A,x,C,C;' where teoremaid=112;
UPDATE teorema SET enunciado='= T (c_{12} (\Phi_{(bccbbbb,bb)} c_{14} c_{16} \Phi_{b} \Phi_{bbb} c_{12} \Phi_{b} c_{17} \Phi_{b} c_{16}) (\Phi_{b} (c_{59} c_{18})))' where id=113;
UPDATE resuelve SET variables='A,B,x,x,y,y;' where teoremaid=113;
UPDATE teorema SET enunciado='= T (c_{13} (\Phi_{(bb(ccbb,b),cb)} c_{5} c_{11} c_{20} c_{24} (\Phi_{(bb(bb,),b)} c_{2}) c_{16} c_{16} c_{18} c_{16}))' where id=114;
UPDATE resuelve SET variables='A,x;' where teoremaid=114;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bcbbb} c_{13} c_{16} (\Phi_{bbb} c_{11}) (\Phi_{(bb,b)} c_{1}) c_{27}))' where id=115;
UPDATE resuelve SET variables='B,A,x;' where teoremaid=115;
UPDATE teorema SET enunciado='= (\Phi_{cb} c_{15} (\Phi_{(bbb,b)} \Phi_{bb} c_{2})) (\Phi_{cbb} c_{15} \Phi_{bb} (\Phi_{(bb,b)} c_{2}))' where id=98;
UPDATE resuelve SET variables=';E,f,e' where teoremaid=98;
UPDATE teorema SET enunciado='= c_{8} (c_{11} (\Phi_{K} c_{8}))' where id=116;
UPDATE resuelve SET variables='x;' where teoremaid=116;
UPDATE teorema SET enunciado='= (\Phi_{K} T) (\Phi_{(b,)} c_{1})' where id=10;
UPDATE resuelve SET variables=';q' where teoremaid=10;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bb} c_{11}) (\Phi_{(bb,b)} c_{2})) (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12} \Phi_{b})' where id=117;
UPDATE resuelve SET variables='x,x,x;P,R' where teoremaid=117;
UPDATE teorema SET enunciado='= (\Phi_{bcb} (\Phi_{bb} c_{11}) c_{7} (\Phi_{(bb,bb)} c_{4})) (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12} \Phi_{b})' where id=118;
UPDATE resuelve SET variables='x,x,x;P,R' where teoremaid=118;
UPDATE teorema SET enunciado='= (\Phi_{(b,cb)} (\Phi_{bcb} c_{11}) c_{5} (\Phi_{(bb,(bb,b))} c_{1})) (\Phi_{ccbb} \Phi_{b} c_{12} \Phi_{cbb} \Phi_{b})' where id=119;
UPDATE resuelve SET variables='x,x,x;R,P' where teoremaid=119;
UPDATE teorema SET enunciado='= (\Phi_{b(cb,)} (\Phi_{bb} c_{11}) c_{4} (\Phi_{(bb,(bb,b))} c_{1})) (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12} \Phi_{b})' where id=120;
UPDATE resuelve SET variables='x,x,x;P,R' where teoremaid=120;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12}) (\Phi_{(bb,b)} c_{2})) (\Phi_{cbbbb} (\Phi_{(bb,b)} c_{5}) \Phi_{bb} \Phi_{bb} c_{12} \Phi_{b})' where id=121;
UPDATE resuelve SET variables='x,x,x,x;P,R,Q' where teoremaid=121;
UPDATE teorema SET enunciado='= (\Phi_{bcb} (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12}) c_{7} (\Phi_{(bb,bb)} c_{4})) (\Phi_{cbbbb} (\Phi_{(bb,b)} c_{5}) \Phi_{bb} \Phi_{bb} c_{12} \Phi_{b})' where id=122;
UPDATE resuelve SET variables='x,x,x,x;P,R,Q' where teoremaid=122;
UPDATE teorema SET enunciado='= (\Phi_{(b,cb)} (\Phi_{cbbcb} \Phi_{b} \Phi_{bb} c_{12}) c_{5} (\Phi_{(bb,(bb,b))} c_{1})) (\Phi_{cccbb} \Phi_{b} c_{12} \Phi_{bb} \Phi_{cbbb} (\Phi_{(bb,b)} c_{5}))' where id=123;
UPDATE resuelve SET variables='x,x,x,x;R,P,Q' where teoremaid=123;
UPDATE teorema SET enunciado='= (\Phi_{b(cb,)} (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12}) c_{4} (\Phi_{(bb,(bb,b))} c_{1})) (\Phi_{cbbbb} (\Phi_{(bb,b)} c_{5}) \Phi_{bb} \Phi_{bb} c_{12} \Phi_{b})' where id=124;
UPDATE resuelve SET variables='x,x,x,x;P,R,Q' where teoremaid=124;
UPDATE teorema SET enunciado='= (\Phi_{ccb} \Phi_{cbb} c_{4} (\Phi_{cbbccb} \Phi_{b} \Phi_{bb} c_{12})) (\Phi_{ccbbb} \Phi_{cbbb} c_{4} (\Phi_{cccb} \Phi_{b}) c_{12} \Phi_{b})' where id=125;
UPDATE resuelve SET variables='x,x,x,x;Q,P,R' where teoremaid=125;
UPDATE teorema SET enunciado='= (\Phi_{bbbb} \Phi_{b} c_{4} c_{11} (\Phi_{bb} c_{7})) (\Phi_{ccbb} \Phi_{K} c_{12} \Phi_{cbb} \Phi_{b})' where id=126;
UPDATE resuelve SET variables='x,x,x;R,P' where teoremaid=126;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{cc(ccccccccb,bb)} \Phi_{b} \Phi_{b} c_{5} (\Phi_{bb} c_{7}) c_{11} c_{7} \Phi_{cb(bb,cbccb)} c_{2} c_{1} c_{12} (\Phi_{cccc((ccbbbb,bbb),b)} \Phi_{cbb} c_{5}) c_{12} \Phi_{b})' where id=127;
UPDATE resuelve SET variables='x,x,x,x,x;Q,R,P' where teoremaid=127;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{ccc(cccccbb,bb)} \Phi_{b} \Phi_{b} \Phi_{b} c_{1} (\Phi_{(bbcbb,cbb)} c_{2}) c_{12} \Phi_{b} c_{12} \Phi_{cc(cc(bbbb,b),b)} (\Phi_{(bb,b)} c_{1}) c_{12} \Phi_{b})' where id=128;
UPDATE resuelve SET variables='x,x,x,x,x,x;Q,R,P' where teoremaid=128;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{c(ccbbb,bb)} \Phi_{b} c_{2} \Phi_{bbcb} (\Phi_{c(cbbbb,)} (\Phi_{(bb,b)} c_{4})) c_{12} \Phi_{b} c_{12} \Phi_{b})' where id=129;
UPDATE resuelve SET variables='x,x,x,x;P,Q,R' where teoremaid=129;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{cc(cccb,bb)} \Phi_{b} \Phi_{b} c_{2} \Phi_{bcbcb} c_{12} (\Phi_{ccc(bbbb,b)} (\Phi_{(bb,b)} c_{5})) c_{12} \Phi_{b})' where id=130;
UPDATE resuelve SET variables='x,x,x,x;P,R,Q' where teoremaid=130;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{ccc(cccccbb,bb)} \Phi_{b} \Phi_{b} \Phi_{b} c_{2} (\Phi_{(bbcbb,cbb)} c_{2}) c_{12} \Phi_{b} c_{12} \Phi_{cc(cc(bbbb,b),b)} (\Phi_{(bb,b)} c_{2}) c_{12} \Phi_{b})' where id=131;
UPDATE resuelve SET variables='x,x,x,x,x,x;P,R,Q' where teoremaid=131;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(cbbb,)} c_{2} \Phi_{cbb} c_{11} \Phi_{b})' where id=132;
UPDATE resuelve SET variables='x;P,e' where teoremaid=132;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} \Phi_{b} (\Phi_{bbb} c_{7}) c_{12} (\Phi_{bb} c_{7})) (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{14} \Phi_{b})' where id=133;
UPDATE resuelve SET variables='x,x,x,x;P,R' where teoremaid=133;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12} \Phi_{b}) (\Phi_{cbbb} \Phi_{b} (\Phi_{bbb} c_{7}) c_{14} (\Phi_{bb} c_{7}))' where id=134;
UPDATE resuelve SET variables='x,x,x,x;P,R' where teoremaid=134;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12} (\Phi_{bb} c_{7})) (\Phi_{cbbb} \Phi_{b} (\Phi_{bbb} c_{7}) c_{14} \Phi_{b})' where id=135;
UPDATE resuelve SET variables='x,x,x,x;P,R' where teoremaid=135;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} \Phi_{b} (\Phi_{bbb} c_{7}) c_{12} \Phi_{b}) (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{14} (\Phi_{bb} c_{7}))' where id=136;
UPDATE resuelve SET variables='x,x,x,x;P,R' where teoremaid=136;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bb} c_{13}) (\Phi_{(bb,b)} c_{5})) (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{14} \Phi_{b})' where id=137;
UPDATE resuelve SET variables='x,x,x;P,R' where teoremaid=137;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{14}) (\Phi_{(bb,b)} c_{5})) (\Phi_{cbbbb} (\Phi_{(bb,b)} c_{5}) \Phi_{bb} \Phi_{bb} c_{14} \Phi_{b})' where id=138;
UPDATE resuelve SET variables='x,x,x,x;P,R,Q' where teoremaid=138;
UPDATE teorema SET enunciado='= (\Phi_{ccb} \Phi_{cbb} c_{5} (\Phi_{cbbccb} \Phi_{b} \Phi_{bb} c_{14})) (\Phi_{ccbbb} \Phi_{cbbb} c_{5} (\Phi_{cccb} \Phi_{b}) c_{14} \Phi_{b})' where id=139;
UPDATE resuelve SET variables='x,x,x,x;Q,P,R' where teoremaid=139;
UPDATE teorema SET enunciado='= (\Phi_{bbbb} \Phi_{b} c_{5} c_{13} \Phi_{b}) (\Phi_{ccbb} \Phi_{K} c_{14} \Phi_{cbb} \Phi_{b})' where id=140;
UPDATE resuelve SET variables='x,x,x;R,P' where teoremaid=140;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{cc(cccccccb,bb)} \Phi_{b} \Phi_{b} c_{4} \Phi_{b} c_{13} \Phi_{cb(bb,cbccb)} c_{2} c_{1} c_{14} (\Phi_{cccc((ccbbb,bbb),b)} \Phi_{cbb} c_{4}) c_{14} \Phi_{b})' where id=141;
UPDATE resuelve SET variables='x,x,x,x,x;Q,R,P' where teoremaid=141;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{9}) (\Phi_{bb} (c_{14} (\Phi_{K} c_{9})) \Phi_{b})' where id=142;
UPDATE resuelve SET variables='x,x;R' where teoremaid=142;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{cc(ccbbb,bb)} (\Phi_{(bb,b)} c_{4}) \Phi_{b} \Phi_{cbbb} c_{2} \Phi_{(ccbbb,b)} c_{14} \Phi_{b} c_{14} \Phi_{b})' where id=143;
UPDATE resuelve SET variables='x,x,x,x;P,R,Q' where teoremaid=143;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{ccbb} \Phi_{b} c_{14} (\Phi_{c(cbbb,bb)} \Phi_{b} \Phi_{b} (\Phi_{(bbb,bb)} c_{2}) c_{14}) (\Phi_{(bb,b)} c_{4}))' where id=144;
UPDATE resuelve SET variables='x,x,x,x;Q,P,R' where teoremaid=144;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{ccc(cccccbb,bb)} \Phi_{b} \Phi_{b} \Phi_{b} c_{2} (\Phi_{(bbcbb,cbb)} c_{2}) c_{14} \Phi_{b} c_{12} \Phi_{cc(cc(bbbb,b),b)} (\Phi_{(bb,b)} c_{2}) c_{14} \Phi_{b})' where id=145;
UPDATE resuelve SET variables='x,x,x,x,x,x;P,R,Q' where teoremaid=145;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(bbbb,)} \Phi_{bb} c_{2} c_{13} \Phi_{b})' where id=146;
UPDATE resuelve SET variables='x;P,E' where teoremaid=146;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{cccc(cccccb,)} \Phi_{b} \Phi_{b} \Phi_{cbcb} c_{14} \Phi_{cb} c_{12} (\Phi_{(bbb,cbcccbb)} c_{2}) \Phi_{b} c_{14} (\Phi_{cccccc(cbbcccbb,b)} \Phi_{b} \Phi_{cbbb} c_{12} \Phi_{b}))' where id=147;
UPDATE resuelve SET variables='x,y,y,y,y,z,x,x;P,R,Q' where teoremaid=147;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bb} c_{7}) c_{16}) (\Phi_{bb} \Phi_{b} c_{17})' where id=148;
UPDATE resuelve SET variables=';A,x' where teoremaid=148;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{b} (c_{17} c_{18})))' where id=149;
UPDATE resuelve SET variables='x;' where teoremaid=149;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{15}) (\Phi_{bbb} \Phi_{b} c_{16} c_{20})' where id=151;
UPDATE resuelve SET variables=';a,x' where teoremaid=151;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{16} \Phi_{bcb} c_{4}) c_{16}) (\Phi_{cccbb} \Phi_{cbbb} c_{16} c_{20} \Phi_{cccb} c_{21})' where id=152;
UPDATE resuelve SET variables=';b,x,a' where teoremaid=152;
UPDATE teorema SET enunciado='= (\Phi_{ccbbcb} c_{16} \Phi_{b} \Phi_{bbb} c_{14} c_{16} \Phi_{cb}) (\Phi_{ccb} c_{22} c_{16} \Phi_{cbb})' where id=153;
UPDATE resuelve SET variables='C,C;x,B' where teoremaid=153;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bbb} c_{22} c_{20}) c_{21}) (\Phi_{bb} \Phi_{b} c_{24})' where id=154;
UPDATE resuelve SET variables=';B,A' where teoremaid=154;
UPDATE teorema SET enunciado='= (\Phi_{(ccbbb,b)} \Phi_{K} c_{16} (\Phi_{(bbb,bb)} c_{19}) (\Phi_{(bb,b)} c_{5}) c_{16} c_{24}) (\Phi_{bb} \Phi_{b} c_{25})' where id=155;
UPDATE resuelve SET variables='x,x;B,A' where teoremaid=155;
UPDATE teorema SET enunciado='= (\Phi_{ccbbb} \Phi_{K} c_{16} (\Phi_{(bbb,b)} c_{19}) (\Phi_{(bb,b)} c_{5}) c_{17}) (\Phi_{bb} \Phi_{b} c_{30})' where id=157;
UPDATE resuelve SET variables='x,x;B,A' where teoremaid=157;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} c_{16} (\Phi_{bbb} c_{11}) (\Phi_{(bb,b)} c_{2}) c_{16}) (\Phi_{bb} \Phi_{b} c_{27})' where id=158;
UPDATE resuelve SET variables='x;B,A' where teoremaid=158;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{27}) (\Phi_{cb} c_{29} \Phi_{cb})' where id=159;
UPDATE resuelve SET variables=';A,B' where teoremaid=159;
UPDATE teorema SET enunciado='= (\Phi_{(bb,b)} (\Phi_{(bb,b)} c_{5}) c_{59} c_{27}) (\Phi_{bb} \Phi_{b} c_{26})' where id=160;
UPDATE resuelve SET variables=';B,A' where teoremaid=160;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{26}) (\Phi_{cb} c_{28} \Phi_{cb})' where id=161;
UPDATE resuelve SET variables=';A,B' where teoremaid=161;
UPDATE teorema SET enunciado='= (\Phi_{cbb} c_{20} (\Phi_{b(bbb,b)} c_{20} c_{21} c_{20}) c_{21}) (\Phi_{bb} \Phi_{b} c_{31})' where id=162;
UPDATE resuelve SET variables=';b,a' where teoremaid=162;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{27}) (\Phi_{bbb} \Phi_{b} c_{16} c_{35})' where id=163;
UPDATE resuelve SET variables=';A,B' where teoremaid=163;
UPDATE teorema SET enunciado='= (\Phi_{(bb,)} c_{24} c_{20}) (\Phi_{b} c_{52})' where id=164;
UPDATE resuelve SET variables=';x' where teoremaid=164;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bbb} c_{13} \Phi_{b} c_{17}))' where id=165;
UPDATE resuelve SET variables='B,A;' where teoremaid=165;
UPDATE teorema SET enunciado='= (\Phi_{(bcccbbb,bb)} c_{19} \Phi_{cb} c_{16} c_{12} \Phi_{cbcb} \Phi_{b} c_{16} \Phi_{K} c_{22}) (\Phi_{b} c_{23})' where id=156;
UPDATE resuelve SET variables='x,C,C,x;B' where teoremaid=156;
UPDATE teorema SET enunciado='= (\Phi_{(ccccccbbb,b)} c_{35} c_{35} \Phi_{K} c_{16} (\Phi_{bcccb} c_{13}) c_{5} (\Phi_{(bcccbb,bbbb)} c_{19} (\Phi_{bc(ccbbb,)} c_{13} c_{31} c_{15})) (\Phi_{(bb,bcbcb)} c_{5}) c_{16} c_{24}) (\Phi_{bb} \Phi_{b} c_{32})' where id=167;
UPDATE resuelve SET variables='x,a,b,x;B,A' where teoremaid=167;
UPDATE teorema SET enunciado='= (\Phi_{b} (\Phi_{c(bb,)} c_{16} (\Phi_{(bb,cb)} c_{5}))) (\Phi_{cccb} \Phi_{cb(bcb,b)} c_{16} c_{19} (\Phi_{cccccb} \Phi_{K} \Phi_{cb}))' where id=150;
UPDATE resuelve SET variables='x,x;P,y,U' where teoremaid=150;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{9}) (\Phi_{(b,b)} c_{1} c_{7})' where id=169;
UPDATE resuelve SET variables=';p' where teoremaid=169;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{(bb,)} c_{2}) c_{5}) (\Phi_{bb} \Phi_{b} c_{2})' where id=170;
UPDATE resuelve SET variables=';q,p' where teoremaid=170;
UPDATE teorema SET enunciado='= (\Phi_{bb} c_{11} \Phi_{b}) (\Phi_{cbb} (\Phi_{K} c_{8}) c_{12} \Phi_{b})' where id=171;
UPDATE resuelve SET variables='x,x,x;P' where teoremaid=171;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{8}) (\Phi_{cbb} (\Phi_{K} c_{9}) c_{12} \Phi_{b})' where id=172;
UPDATE resuelve SET variables='x,x;P' where teoremaid=172;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{cbbb} \Phi_{b} \Phi_{bb} c_{12}) (\Phi_{(bb,b)} c_{5})) (\Phi_{ccbcbbb} \Phi_{b} c_{12} (\Phi_{cbbb} \Phi_{b}) \Phi_{b} (\Phi_{(bbb,bb)} c_{5}) c_{12} \Phi_{b})' where id=173;
UPDATE resuelve SET variables='x,x,x,x,x,x;Q,P,R' where teoremaid=173;
UPDATE teorema SET enunciado='= (\Phi_{c(ccbbb,bb)} \Phi_{b} c_{5} \Phi_{bbb} (\Phi_{ccbbbb} \Phi_{b}) c_{12} \Phi_{b} c_{12} \Phi_{b}) (\Phi_{cbbbb} (\Phi_{(bb,b)} c_{4}) \Phi_{bb} \Phi_{bb} c_{12} \Phi_{b})' where id=174;
UPDATE resuelve SET variables='x,x,x,x,x,x;P,S,R' where teoremaid=174;
UPDATE teorema SET enunciado='= (\Phi_{cccb} \Phi_{b} \Phi_{cbcb} c_{12} (\Phi_{cbbcccbb} \Phi_{b} \Phi_{bb} c_{12} \Phi_{cb})) (\Phi_{cccb} \Phi_{b} \Phi_{cbcccbb} c_{12} (\Phi_{ccccccbb} \Phi_{b} \Phi_{cbbb} c_{12} \Phi_{b}))' where id=175;
UPDATE resuelve SET variables='y,x,x,y,y,x,x,y;P,R,Q' where teoremaid=175;
UPDATE teorema SET enunciado='= (\Phi_{bb} c_{13} \Phi_{b}) (\Phi_{cbb} (\Phi_{K} c_{8}) c_{14} \Phi_{b})' where id=176;
UPDATE resuelve SET variables='x,x,x;P' where teoremaid=176;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bcccc(cb,bbb)} c_{11} c_{17} \Phi_{b} c_{11} c_{5} c_{15} (\Phi_{(bcb,cbbbb)} c_{2}) c_{11} \Phi_{b} c_{17}))' where id=177;
UPDATE resuelve SET variables='A,B,x,x;' where teoremaid=177;
UPDATE teorema SET enunciado='= (\Phi_{K} T) (\Phi_{bcc(ccb,)} c_{11} c_{16} (\Phi_{(b(bcb,b),b)} c_{1} c_{5}) c_{16} (\Phi_{(b(bcb,b),b)} c_{1} c_{5}) (\Phi_{bc(cccccb(cb,b),(cb,b))} c_{11} c_{16} c_{11} (\Phi_{(bcb,cbbbb)} c_{2}) c_{15} c_{5} c_{11} (\Phi_{bcccc(cb,bbb)} c_{11} c_{16})))' where id=178;
UPDATE resuelve SET variables='U,A,B,x,x;P' where teoremaid=178;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bcc(ccbb,b)} c_{11} c_{15} (\Phi_{(b(bb,b),b)} c_{1} c_{4}) c_{15} (\Phi_{(b(bb,b),b)} c_{1} c_{4}) (\Phi_{bc(cccccbcbb,cbb)} c_{11} c_{16} c_{11} (\Phi_{(bcb,cbbbb)} c_{2}) c_{15} c_{5} c_{11} (\Phi_{bcccc(cb,bbb)} c_{11} c_{16})) c_{15} c_{15}))' where id=179;
UPDATE resuelve SET variables='a,b,A,B,x,x;' where teoremaid=179;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bc(cccccbcccbbb,cccbbb)} c_{11} c_{16} c_{11} (\Phi_{(bcb,cbbbb)} c_{2}) c_{15} c_{5} c_{11} (\Phi_{bcccc(cb,bbb)} c_{11} c_{16}) \Phi_{cb} c_{16} c_{14} (\Phi_{(bcbcb,b)} c_{1}) \Phi_{b} c_{16} \Phi_{cb} c_{16} c_{14} (\Phi_{(bcbcb,b)} c_{1}) \Phi_{b} c_{16}))' where id=180;
UPDATE resuelve SET variables='B,A,D,x,C,C,x,C,C;' where teoremaid=180;
UPDATE teorema SET enunciado='= T (c_{11} (\Phi_{bcccc(ccbbb,bb)} c_{11} (\Phi_{(bcb,(bbbb,bbb))} c_{2}) c_{15} c_{5} c_{11} c_{16} c_{11} (\Phi_{bccccccccb} c_{11} c_{16}) (\Phi_{(bb,b)} c_{1}) c_{27} (\Phi_{(bb,b)} c_{1}) c_{27}))' where id=181;
UPDATE resuelve SET variables='B,A,C,x,x;' where teoremaid=181;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{16} \Phi_{bcb} c_{4}) c_{16}) (\Phi_{ccbb} \Phi_{cbb} c_{16} \Phi_{ccb} c_{24})' where id=182;
UPDATE resuelve SET variables=';B,x,A' where teoremaid=182;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{16} \Phi_{bcb} c_{5}) c_{16}) (\Phi_{ccbb} \Phi_{cbb} c_{16} \Phi_{ccb} c_{25})' where id=183;
UPDATE resuelve SET variables=';B,x,A' where teoremaid=183;
UPDATE teorema SET enunciado='= (\Phi_{K} c_{9}) (\Phi_{b} (c_{16} c_{18}))' where id=184;
UPDATE resuelve SET variables=';x' where teoremaid=184;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{ccc(ccbbcb,)} (c_{59} c_{18}) c_{23} c_{16} c_{16} \Phi_{b} (\Phi_{(b(bbbb,cbb),b)} c_{2} c_{1}) c_{12} c_{16} \Phi_{cb})' where id=185;
UPDATE resuelve SET variables='C,C;x,B' where teoremaid=185;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{16} \Phi_{bcb} c_{5}) c_{17}) (\Phi_{ccbb} \Phi_{cbb} c_{16} \Phi_{ccb} c_{30})' where id=186;
UPDATE resuelve SET variables=';B,x,A' where teoremaid=186;
UPDATE teorema SET enunciado='= c_{18} (c_{22} c_{18})' where id=187;
UPDATE resuelve SET variables=';' where teoremaid=187;
UPDATE teorema SET enunciado='= c_{18} (c_{23} c_{18})' where id=188;
UPDATE resuelve SET variables=';' where teoremaid=188;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{24}) (\Phi_{cb} c_{24} \Phi_{cb})' where id=189;
UPDATE resuelve SET variables=';A,B' where teoremaid=189;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(c(cbb,),b)} c_{27} c_{5} (\Phi_{(bb,(bcb,b))} c_{2}) c_{15} c_{27})' where id=190;
UPDATE resuelve SET variables=';B,A' where teoremaid=190;
UPDATE teorema SET enunciado='= (\Phi_{bbb} c_{13} \Phi_{b} c_{16}) (\Phi_{b} (c_{59} c_{18}))' where id=191;
UPDATE resuelve SET variables='x;A' where teoremaid=191;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{24} \Phi_{bcb} c_{25}) c_{24}) (\Phi_{ccbb} \Phi_{cbb} c_{24} \Phi_{ccb} c_{25})' where id=192;
UPDATE resuelve SET variables=';C,A,B' where teoremaid=192;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(ccbbb,b)} (c_{59} c_{18}) c_{5} \Phi_{b(bb,b)} c_{2} (c_{59} c_{18}) c_{27})' where id=193;
UPDATE resuelve SET variables=';B,A' where teoremaid=193;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{c((cbbb,bbbb),)} c_{27} c_{23} (\Phi_{(bbb,bcb)} c_{2}) c_{27} c_{23} c_{5} c_{13} \Phi_{b} c_{16})' where id=194;
UPDATE resuelve SET variables='C;A,B' where teoremaid=194;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{c(cc(ccbbb,b),)} c_{27} (c_{59} c_{18}) c_{5} c_{5} c_{23} (\Phi_{(bbb,(bcbb,cb))} c_{2}) c_{27} c_{23} (c_{59} c_{18}))' where id=195;
UPDATE resuelve SET variables=';A,B' where teoremaid=195;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(bbb,b)} \Phi_{bb} c_{2} (c_{59} c_{18}) c_{16})' where id=196;
UPDATE resuelve SET variables=';B,A' where teoremaid=196;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{cc(cccccbb,b)} c_{16} c_{23} (c_{15} c_{18}) c_{2} \Phi_{b(bbb,b)} c_{5} (c_{15} c_{18}) \Phi_{(cccbbbbb,b)} c_{25} c_{25})' where id=197;
UPDATE resuelve SET variables=';C,B,A' where teoremaid=197;
UPDATE teorema SET enunciado='= c_{18} (c_{23} (c_{20} c_{18}))' where id=198;
UPDATE resuelve SET variables=';' where teoremaid=198;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{bb} (\Phi_{bbb} (c_{59} c_{18}) c_{20}) c_{21})' where id=199;
UPDATE resuelve SET variables=';B,A' where teoremaid=199;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{25}) (\Phi_{bb} (\Phi_{bbb} c_{23} c_{20}) c_{21})' where id=200;
UPDATE resuelve SET variables=';B,A' where teoremaid=200;
UPDATE teorema SET enunciado='= (\Phi_{K} T) (\Phi_{bb} (c_{59} c_{18}) c_{20})' where id=201;
UPDATE resuelve SET variables=';A' where teoremaid=201;
UPDATE teorema SET enunciado='= \Phi_{} (\Phi_{bb} c_{23} c_{20})' where id=202;
UPDATE resuelve SET variables=';A' where teoremaid=202;
UPDATE teorema SET enunciado='= (\Phi_{K} T) (\Phi_{(b,)} c_{17})' where id=203;
UPDATE resuelve SET variables=';A' where teoremaid=203;
UPDATE teorema SET enunciado='= T (c_{7} (c_{13} (\Phi_{bc(bb,)} c_{13} c_{16} (\Phi_{(bb,cb)} c_{5}) c_{16})))' where id=204;
UPDATE resuelve SET variables='A,B;' where teoremaid=204;
UPDATE teorema SET enunciado='= T (c_{7} (c_{13} (\Phi_{bc(cccbb,)} c_{13} c_{16} \Phi_{cb(bb,cb)} c_{5} c_{5} (\Phi_{bc(cccbcb,)} c_{13} c_{16}) c_{16})))' where id=205;
UPDATE resuelve SET variables='A,B,C;' where teoremaid=205;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{bb} c_{20}) c_{21}) (\Phi_{bb} (\Phi_{bb} c_{22}) c_{31})' where id=206;
UPDATE resuelve SET variables=';b,a' where teoremaid=206;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{K} c_{20}) (\Phi_{cb} c_{31} (\Phi_{bcb} c_{23}))' where id=207;
UPDATE resuelve SET variables=';a,b' where teoremaid=207;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{c(c(bb,),)} c_{59} c_{31} (\Phi_{(b(bb,cb),cb)} c_{2} c_{59}) c_{31})' where id=208;
UPDATE resuelve SET variables=';a,b' where teoremaid=208;
UPDATE teorema SET enunciado='= (\Phi_{bb} \Phi_{b} c_{15}) (\Phi_{cbbb} c_{20} \Phi_{bb} c_{15} c_{20})' where id=209;
UPDATE resuelve SET variables=';b,a' where teoremaid=209;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{cbbbb} c_{15} \Phi_{bb} \Phi_{bb} c_{5}) c_{15}) (\Phi_{ccccbb} c_{31} \Phi_{cbbb} \Phi_{bb} c_{15} \Phi_{cccbb} c_{31})' where id=210;
UPDATE resuelve SET variables=';d,b,c,a' where teoremaid=210;
UPDATE teorema SET enunciado='= (\Phi_{ccccbb} c_{16} (\Phi_{bccccb} c_{13}) (\Phi_{(bcbb,cbcb)} c_{5}) c_{5} (\Phi_{ccccbb} (\Phi_{bc(ccccbb,)} c_{13} c_{31} c_{15})) c_{16}) (\Phi_{bb} (\Phi_{bbb} \Phi_{b} c_{16}) c_{32})' where id=211;
UPDATE resuelve SET variables='a,b;B,A,x' where teoremaid=211;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{cbbbb} c_{16} \Phi_{bb} \Phi_{bb} c_{5}) c_{16}) (\Phi_{ccccbb} c_{31} \Phi_{cbbb} \Phi_{bb} c_{16} \Phi_{cccbb} c_{32})' where id=212;
UPDATE resuelve SET variables=';B,b,A,a' where teoremaid=212;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} (c_{15} c_{18}) \Phi_{bb} c_{4} (c_{15} c_{18})) (\Phi_{bb} (\Phi_{bb} (c_{15} c_{18})) c_{32})' where id=213;
UPDATE resuelve SET variables=';B,A' where teoremaid=213;
UPDATE teorema SET enunciado='= (\Phi_{c(ccbbb,bb)} c_{16} c_{13} c_{17} (\Phi_{(bbbb,bbb)} c_{4} c_{13}) (\Phi_{(bb,b)} c_{5}) c_{16} (\Phi_{(bb,b)} c_{5}) c_{17}) (\Phi_{bb} \Phi_{b} c_{59})' where id=214;
UPDATE resuelve SET variables='x,x;B,A' where teoremaid=214;
UPDATE teorema SET enunciado='= (\Phi_{c(bb,bb)} (c_{15} c_{18}) (\Phi_{(bb,bb)} c_{4}) c_{15} c_{4} (c_{15} c_{18})) (\Phi_{(cb,b)} c_{32} (\Phi_{(bcb,b)} c_{15}) c_{32})' where id=215;
UPDATE resuelve SET variables=';B,A' where teoremaid=215;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{cbc(bbbbcb,)} c_{32} \Phi_{bb} c_{16} \Phi_{bcbb} c_{2} c_{13} (\Phi_{bcb} c_{13} c_{31}) c_{15} \Phi_{cbcb})' where id=216;
UPDATE resuelve SET variables='a,b;x,B,A' where teoremaid=216;
UPDATE teorema SET enunciado='= (\Phi_{bb} (\Phi_{c(bbb,)} c_{32} \Phi_{bcb} c_{25}) c_{32}) (\Phi_{ccbb} \Phi_{cbb} c_{32} \Phi_{ccb} c_{25})' where id=217;
UPDATE resuelve SET variables=';C,A,B' where teoremaid=217;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} (\Phi_{K} T))) (\Phi_{(cbb,b)} c_{16} (\Phi_{(bbbbb,bb)} (\Phi_{(bb,b)} c_{2}) c_{16} c_{22} c_{22}) c_{24} c_{34})' where id=218;
UPDATE resuelve SET variables=';S,R,w' where teoremaid=218;
UPDATE teorema SET enunciado='= (\Phi_{ccbbb} c_{16} (\Phi_{bccccb} c_{13} (\Phi_{(bbcccbb,cbcb)} c_{5} c_{13} c_{31})) (\Phi_{cccbb} (\Phi_{bc(cccccb,)} c_{13} c_{31} c_{15}) c_{31}) (\Phi_{(bbb,bcb)} c_{5}) c_{16}) (\Phi_{cb} c_{34} (\Phi_{bbcb} \Phi_{b} c_{16}))' where id=219;
UPDATE resuelve SET variables='x,y,z;S,R,w' where teoremaid=219;
UPDATE teorema SET enunciado='= (\Phi_{(ccbb,b)} c_{24} \Phi_{bb} \Phi_{cbbb} c_{34} c_{34}) (\Phi_{cbbb} c_{24} \Phi_{bb} \Phi_{bb} c_{34})' where id=220;
UPDATE resuelve SET variables=';A,C,B' where teoremaid=220;
UPDATE teorema SET enunciado='= (\Phi_{K} (\Phi_{K} T)) (\Phi_{(ccbbb,b)} c_{60} c_{60} (\Phi_{(bbb,bb)} c_{27}) c_{25} c_{60} c_{25})' where id=221;
UPDATE resuelve SET variables=';S,R' where teoremaid=221;
UPDATE teorema SET enunciado='= (\Phi_{(bbbb,bbb)} c_{19} (\Phi_{bcb} c_{13} c_{31}) \Phi_{bcb} c_{16} \Phi_{K} c_{22} c_{22}) (\Phi_{b} c_{60})' where id=222;
UPDATE resuelve SET variables='x,y,x;R' where teoremaid=222;
UPDATE teorema SET enunciado='= (\Phi_{(bcbbb,bbb)} c_{19} c_{31} (\Phi_{bbb} c_{13}) \Phi_{bb} c_{16} \Phi_{K} c_{22} c_{22}) (\Phi_{b} c_{61})' where id=223;
UPDATE resuelve SET variables='y,x,y;R' where teoremaid=223;
UPDATE teorema SET enunciado='= (\Phi_{bbb} (\Phi_{bcb} c_{13} c_{31}) \Phi_{bcb} c_{16}) (\Phi_{bbb} \Phi_{b} c_{16} c_{60})' where id=224;
UPDATE resuelve SET variables='y;R,z' where teoremaid=224;
UPDATE teorema SET enunciado='= (\Phi_{cbbb} c_{31} (\Phi_{bbb} c_{13}) \Phi_{bb} c_{16}) (\Phi_{bbb} \Phi_{b} c_{16} c_{61})' where id=225;
UPDATE resuelve SET variables='x;R,z' where teoremaid=225;
UPDATE teorema SET enunciado='= (\Phi_{(b,)} c_{15}) (\Phi_{K} c_{8})' where id=226;
UPDATE resuelve SET variables=';q' where teoremaid=226;