package com.calclogic.entity;

// Generated Feb 27, 2019 12:50:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.*;
import java.io.Serializable;

/**
 * mostrarCategoria generated by hbm2java
 *
 * <p>This table implements the relation between the users and the categories (objects of the
 * "Categoria" table) that they can see.
 */
@Entity
public class MostrarCategoria implements Serializable {

  //  @Id
  //  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "mostrarcategoria_id_seq")
  //  @SequenceGenerator(
  //      name = "mostrarcategoria_id_seq",
  //      sequenceName = "mostrarcategoria_id_seq",
  //      allocationSize = 1)
  //  private int id;

  @EmbeddedId private MostrarCategoriaId id;

  public MostrarCategoria() {}

  public MostrarCategoria(Categoria categoria, Usuario usuario) {
    this.id = new MostrarCategoriaId(usuario, categoria);
  }

  // Getter y setter para el id (la clave compuesta)
  public MostrarCategoriaId getId() {
    return id;
  }

  public void setId(MostrarCategoriaId id) {
    this.id = id;
  }
}
