package com.calclogic.entity;
// Generated Feb 27, 2019 12:50:11 PM by Hibernate Tools 3.2.1.GA

/**
 * mostrarCategoria generated by hbm2java
 *
 * This table implements the relation between the users and
 * the categories (objects of the "Categoria" table) that they
 * can see.
 */
public class MostrarCategoria  implements java.io.Serializable {

     private Categoria categoria;
     private Usuario usuario;

    
     public MostrarCategoria(){;}
     
    public MostrarCategoria(Categoria categoria, Usuario usuario) {
        this.categoria = categoria;
        this.usuario = usuario;
    }

    public Categoria getCategoria() {
        return categoria;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
     
     
     
}
