package com.howtodoinjava.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * Categoria generated by hbm2java
 */
public class Materia  implements java.io.Serializable {
    
    @Id
    @Column(name="id")
    @GeneratedValue( strategy= GenerationType.SEQUENCE, generator="categoria_id_seq")
    @SequenceGenerator(name="categoria_id_seq", sequenceName="categoria_id_seq")
     private int id;
     private String nombre;
     private Set usuarios = new HashSet(0);

    public Materia() {
    }

    public Materia(String nombre) {
        this.nombre = nombre;
    }

    
    public Materia(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Materia(int id, String nombre, Set usuarios) {
       this.id = id;
       this.nombre = nombre;
       this.usuarios =usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
}