package com.howtodoinjava.entity;
// Generated Feb 27, 2019 12:50:11 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * mostrarCategoria generated by hbm2java
 */
public class MostrarCategoria  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue( strategy= GenerationType.SEQUENCE, generator="mostrarCategoria_id_seq")
    @SequenceGenerator(name="mostrarCategoria_id_seq", sequenceName="mostrarCategoria_id_seq")
     private int id;
     private Categoria categoria;
     private Usuario usuario;

    
     public MostrarCategoria(){;}
     
    public MostrarCategoria(Categoria categoria, Usuario usuario) {
        this.categoria = categoria;
        this.usuario = usuario;
    }

    public int getId() {
        return id;
    }

    public Categoria getCategoria() {
        return categoria;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
     
     
     
}
