package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA

import com.howtodoinjava.lambdacalculo.Term;
import org.springframework.util.SerializationUtils;




/**
 * Predicado generated by hbm2java
 */
public class Predicado  implements java.io.Serializable {


     private PredicadoId id;
     private Usuario usuario;
     private String predicado;
     private String alias;
     private byte[] predserializado;
     private String argumentos;
     private Term term;

    public Predicado() {
    }

    public Predicado(PredicadoId id, Usuario usuario, String predicado, String alias, byte[] predserializado, String argumentos) {
       this.id = id;
       this.usuario = usuario;
       this.predicado = predicado;
       this.alias = alias;
       this.predserializado = predserializado;
       this.argumentos = argumentos;
    }
   
    public PredicadoId getId() {
        return this.id;
    }
    
    public void setId(PredicadoId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPredicado() {
        return this.predicado;
    }
    
    public void setPredicado(String predicado) {
        this.predicado = predicado;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public byte[] getPredserializado() {
        return this.predserializado;
    }
    
    public void setPredserializado(Term t) {
        this.predserializado= SerializationUtils.serialize(t);
    }
    
    public void setPredserializado(byte[] predserializado) {
        this.predserializado = predserializado;
    }
    public String getArgumentos() {
        return this.argumentos;
    }
    
    public void setArgumentos(String argumentos) {
        this.argumentos = argumentos;
    }
    
    public void setTerm(Term t) {
        term = t;
    }
    
    public Term getTerm() {
        return term;
    }




}


