package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA



/**
 * PredicadoId generated by hbm2java
 */
public class PredicadoId  implements java.io.Serializable {


     private int id;
     private String loginusuario;

    public PredicadoId() {
    }

    public PredicadoId(int id, String loginusuario) {
       this.id = id;
       this.loginusuario = loginusuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLoginusuario() {
        return this.loginusuario;
    }
    
    public void setLoginusuario(String loginusuario) {
        this.loginusuario = loginusuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PredicadoId) ) return false;
		 PredicadoId castOther = ( PredicadoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getLoginusuario()==castOther.getLoginusuario()) || ( this.getLoginusuario()!=null && castOther.getLoginusuario()!=null && this.getLoginusuario().equals(castOther.getLoginusuario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getLoginusuario() == null ? 0 : this.getLoginusuario().hashCode() );
         return result;
   }   


}


