package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA



/**
 * Predicado generated by hbm2java
 */
public class Predicado  implements java.io.Serializable {


     private PredicadoId id;
     private Usuario usuario;
     private String predicado;
     private String alias;
     private String predserializado;
     private int numargumentos;

    public Predicado() {
    }

    public Predicado(PredicadoId id, Usuario usuario, String predicado, String alias, String predserializado, int numargumentos) {
       this.id = id;
       this.usuario = usuario;
       this.predicado = predicado;
       this.alias = alias;
       this.predserializado = predserializado;
       this.numargumentos = numargumentos;
    }
   
    public PredicadoId getId() {
        return this.id;
    }
    
    public void setId(PredicadoId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPredicado() {
        return this.predicado;
    }
    
    public void setPredicado(String predicado) {
        this.predicado = predicado;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getPredserializado() {
        return this.predserializado;
    }
    
    public void setPredserializado(String predserializado) {
        this.predserializado = predserializado;
    }
    public int getNumargumentos() {
        return this.numargumentos;
    }
    
    public void setNumargumentos(int numargumentos) {
        this.numargumentos = numargumentos;
    }




}


