package com.howtodoinjava.entity;
// Generated 27/06/2014 08:05:40 PM by Hibernate Tools 3.2.1.GA



/**
 * PublicacionId generated by hbm2java
 */
public class PublicacionId  implements java.io.Serializable {


     private String alias;
     private String login;

    public PublicacionId() {
    }

    public PublicacionId(String alias, String login) {
       this.alias = alias;
       this.login = login;
    }
   
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PublicacionId) ) return false;
		 PublicacionId castOther = ( PublicacionId ) other; 
         
		 return ( (this.getAlias()==castOther.getAlias()) || ( this.getAlias()!=null && castOther.getAlias()!=null && this.getAlias().equals(castOther.getAlias()) ) )
 && ( (this.getLogin()==castOther.getLogin()) || ( this.getLogin()!=null && castOther.getLogin()!=null && this.getLogin().equals(castOther.getLogin()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAlias() == null ? 0 : this.getAlias().hashCode() );
         result = 37 * result + ( getLogin() == null ? 0 : this.getLogin().hashCode() );
         return result;
   }   


}


