package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA


import com.howtodoinjava.lambdacalculo.Term;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import org.springframework.util.SerializationUtils;

/**
 * Teorema generated by hbm2java
 */
public class Teorema  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue( strategy= GenerationType.SEQUENCE, generator="teorema_id_seq")
    @SequenceGenerator(name="teorema_id_seq", sequenceName="teorema_id_seq")
     private int id;
     private Categoria categoria;
     private String enunciado;
     private byte[] teoserializado;
     private Term teoTerm;
     private Term metateoTerm;
     private boolean esquema;
     private Set resuelves = new HashSet(0);

    public Teorema() {
    }

    public Teorema(Categoria categoria, String enunciado, Term teoTerm, boolean esquema) {
        this.categoria = categoria;
        this.enunciado = enunciado;
        this.teoserializado = SerializationUtils.serialize(teoTerm);
        this.teoTerm = teoTerm;
        this.esquema = esquema;
    }

    public void setMetateoTerm(Term metateoTerm) {
        this.metateoTerm = metateoTerm;
    }

    public Term getMetateoTerm() {
        return metateoTerm;
    }

    public void setTeoTerm(Term teoTerm) {
        this.teoTerm = teoTerm;
        this.teoserializado = SerializationUtils.serialize(teoTerm);
    }

    public Term getTeoTerm() {
        return teoTerm;
    }
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }
    public String getEnunciado() {
        return this.enunciado;
    }

    public void setTeoserializado(byte[] teoserializado) {
        this.teoserializado = teoserializado;
    }

    public void setResuelves(Set resuelves) {
        this.resuelves = resuelves;
    }

    public byte[] getTeoserializado() {
        return teoserializado;
    }

    public Set getResuelves() {
        return resuelves;
    }

    public boolean isEsquema() {
        return esquema;
    }

    public void setEsquema(boolean esquema) {
        this.esquema = esquema;
    }
}

