package com.howtodoinjava.entity;
// Generated Feb 27, 2019 12:50:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * Teoria generated by hbm2java
 */
public class Teoria  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue( strategy= GenerationType.SEQUENCE, generator="teoria_id_seq")
    @SequenceGenerator(name="teoria_id_seq", sequenceName="teoria_id_seq")
     private int id;
     private String nombre;


    public Teoria() {
    }

    public Teoria(String nombre) {
        this.nombre = nombre;
    }
    
    public int getId() {
        return this.id;
    }
   
    
    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    




}
