package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA


import com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer;
import com.howtodoinjava.lambdacalculo.Term;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import org.springframework.util.SerializationUtils;
import org.stringtemplate.v4.compiler.CodeGenerator.includeExpr_return;

/**
 * Teorema generated by hbm2java
 */
public class Teorema  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue( strategy= GenerationType.SEQUENCE, generator="teorema_id_seq")
    @SequenceGenerator(name="teorema_id_seq", sequenceName="teorema_id_seq")
     private int id;
     private String enunciado;
     private Term teoTerm;
     private Term metateoTerm;
     private boolean esquema;
     private String aliases;
     private Set resuelves = new HashSet(0);

    public Teorema() {
    }

    public Teorema(String enunciado, Term teoTerm, boolean esquema, String aliases) {
        this.enunciado = enunciado;
        this.teoTerm = teoTerm;
        this.esquema = esquema;
        this.aliases = aliases;
        
    }

    public void setMetateoTerm(Term metateoTerm) {
        this.metateoTerm = metateoTerm;
    }

    public Term getMetateoTerm() {
        return metateoTerm;
    }

    public void setTeoTerm(Term teoTerm) {
    	
    	// Get the aliases list
    	String aliasesString = this.getAliases();
    	String[] aliases = aliasesString.split(",\\s");
    	
    	// In case the list is empty in the database we must make it also an empty array
    	if( aliases[0].equals("") ) {
    		aliases = new String[0];
    	}
    	
    	// Set the alias name of each alias node 
    	
    	String[] aliasPosition;
    	Term aliasTerm;
    	for(String alias : aliases) {
    		   		
    		// Get the position and name of the alias
    		aliasPosition = alias.split(":");
    		
    		// Find the alias term node by its position
    		if( aliasPosition.length == 2) { // if we have a not empty position
    			aliasTerm = teoTerm.subterm(aliasPosition[1]);
    		}else { // if the potition is empty it means the root is an alias
    			aliasTerm = teoTerm.subterm("");
    		}
    		
    		// Set the proper name of that node
    		aliasTerm.alias = aliasPosition[0];
    		
    	}
    	
    	
        this.teoTerm = teoTerm;
    }

    public Term getTeoTerm() {
        return teoTerm;
    }
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }
    public String getEnunciado() {
        return this.enunciado;
    }

    public void setResuelves(Set resuelves) {
        this.resuelves = resuelves;
    }

    public Set getResuelves() {
        return resuelves;
    }

    public boolean isEsquema() {
        return esquema;
    }

    public void setEsquema(boolean esquema) {
        this.esquema = esquema;
    }

	public String getAliases() {
		return aliases;
	}

	public void setAliases(String aliases) {
		this.aliases = aliases;
	}
}
