package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA


import com.howtodoinjava.lambdacalculo.Term;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import org.springframework.util.SerializationUtils;

/**
 * Teorema generated by hbm2java
 */
public class Teorema  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue( strategy= GenerationType.SEQUENCE, generator="teorema_id_seq")
    @SequenceGenerator(name="teorema_id_seq", sequenceName="teorema_id_seq")
     private int id;
     private Categoria categoria;
     private String enunciadoizq;
     private String enunciadoder;
     private byte[] teoserializadoizq;
     private byte[] teoserializadoder;
     private Term teoIzqTerm;
     private Term teoDerTerm;
     private Term teoTerm;
     private Term metateoTerm;
     private String operador;
     private boolean esquema;
     private Set resuelves = new HashSet(0);

    public Teorema() {
    }

    public Teorema(Categoria categoria, String enunciadoizq, String enunciadoder, Term teoIzqTerm, Term teoDerTerm, String operador, boolean esquema) {
        this.categoria = categoria;
        this.enunciadoizq = enunciadoizq;
        this.enunciadoder = enunciadoder;
        this.teoserializadoizq = SerializationUtils.serialize(teoIzqTerm);
        this.teoserializadoder = SerializationUtils.serialize(teoDerTerm);
        this.teoIzqTerm = teoIzqTerm;
        this.teoDerTerm = teoDerTerm;
        this.operador = operador;
        this.esquema = esquema;
    }

    public void setMetateoTerm(Term metateoTerm) {
        this.metateoTerm = metateoTerm;
    }

    public Term getMetateoTerm() {
        return metateoTerm;
    }

    public void setTeoTerm(Term teoTerm) {
        this.teoTerm = teoTerm;
    }

    public Term getTeoTerm() {
        return teoTerm;
    }
    
    public int getId() {
        return this.id;
    }

    public Term getTeoIzqTerm() {
        return teoIzqTerm;
    }

    public Term getTeoDerTerm() {
        return teoDerTerm;
    }

    public void setTeoIzqTerm(Term teoIzqTerm) {
        this.teoIzqTerm = teoIzqTerm;
        this.teoserializadoizq = SerializationUtils.serialize(teoIzqTerm);
    }

    public void setTeoDerTerm(Term teoDerTerm) {
        this.teoDerTerm = teoDerTerm;
        this.teoserializadoder = SerializationUtils.serialize(teoDerTerm);
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getEnunciadoizq() {
        return this.enunciadoizq;
    }
    
    public void setEnunciadoizq(String enunciadoizq) {
        this.enunciadoizq = enunciadoizq;
    }
    public String getEnunciadoder() {
        return this.enunciadoder;
    }
    
    public void setEnunciadoder(String enunciadoder) {
        this.enunciadoder = enunciadoder;
    }
    public String getOperador() {
        return this.operador;
    }
    
    public void setOperador(String operador) {
        this.operador = operador;
    }

    public void setTeoserializadoizq(byte[] teoserializadoizq) {
        this.teoserializadoizq = teoserializadoizq;
    }

    public void setTeoserializadoder(byte[] teoserializadoder) {
        this.teoserializadoder = teoserializadoder;
    }

    public void setResuelves(Set resuelves) {
        this.resuelves = resuelves;
    }

    public byte[] getTeoserializadoizq() {
        return teoserializadoizq;
    }

    public byte[] getTeoserializadoder() {
        return teoserializadoder;
    }

    public Set getResuelves() {
        return resuelves;
    }

    public boolean isEsquema() {
        return esquema;
    }

    public void setEsquema(boolean esquema) {
        this.esquema = esquema;
    }
    

}


