package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA

import com.howtodoinjava.lambdacalculo.Term;
import org.springframework.util.SerializationUtils;




/**
 * Termino generated by hbm2java
 */
public class Termino  implements java.io.Serializable {


     private TerminoId id;
     private Usuario usuario;
     private String combinador;
     private byte[] serializado;
     private Term termobject;

    public Termino() {
    }

	
    public Termino(TerminoId id, Usuario usuario, String combinador, byte[] serializado) {
        this.id = id;
        this.usuario = usuario;
        this.combinador = combinador;
        this.serializado = serializado;
    }
    public Termino(TerminoId id, Usuario usuario, String combinador, byte[] serializado, Term termobject) {
       this.id = id;
       this.usuario = usuario;
       this.combinador = combinador;
       this.serializado = serializado;
       this.termobject = termobject;
    }
   
    public TerminoId getId() {
        return this.id;
    }
    
    public void setId(TerminoId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCombinador() {
        return this.combinador;
    }
    
    public void setCombinador(String combinador) {
        this.combinador = combinador;
    }
    public byte[] getSerializado() {
        return this.serializado;
    }
    
    public void setSerializado(byte[] serializado) {
        this.serializado = serializado;
    }
    public Term getTermObject() {
        return this.termobject;
    }
    
    public void setTermObject(Term t)
    {
         this.termobject=t;
         this.serializado= SerializationUtils.serialize(t);
    }

    @Override
    public String toString()
    {
        return this.termobject.toString();
    }


}


